### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by jerry011235** [guoming0000/BatchRunTrayTool#6]
1. 能否做一个**程序__hide__** ，然后增加一个选项：以隐藏方式来运行脚本。
相当于vbs中`createobject("wscript.shell").run "XXX.bat",0`中`0`的作用（隐藏窗口并激活另一窗口）。
2. 能否做成便携版或压缩包，直接解压就能用。

**Comment by guoming0000** [comment]
@jerry011235 
1. 默认就是hide模式，所有脚本都是隐藏运行的
2. 绿色解压版已经上传，https://github.com/guoming0000/BatchRunTrayTool/releases/tag/v17.7.17
